
name: Deploy to Namecheap
on:
  push:
    branches:
      - main  # Or your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Inject API Key
        run: |
          sed -i "s/__NEWS_API_KEY_PLACEHOLDER__/${{ secrets.NEWS_API_KEY }}/g" index.html

      - name: Deploy via FTP to Namecheap
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
            server: ftp.ruvab.it.com
            username: ${{ secrets.FTP_USERNAME }} # Set this in GitHub Secrets
            password: ${{ secrets.FTP_PASSWORD }} # Set this in GitHub Secrets
            server-dir: /public_html/ # Or your specific folder
